### ISSUE TITLE
Code to reproduce table 7, 9, 11 Failed examples statistics

### ISSUE THREAD

**Issue by pkulium** [xinleihe/toxic-prompt#2]
Hey @xinleihe, quick question:
can we get code to reproduce table 7, 9, 11 for failed examples statistics?

**Comment by xinleihe** [comment]
Hi @pkulium, the examples in those tables are labeled manually so we do not have code for them.

**Comment by pkulium** [comment]
Got it, thanks!

**Comment by pkulium** [comment]
resolved
